#!/usr/bin/env python3
"""Copy the durable Campus Commons SQLite data into Supabase Postgres.

The copy is deliberately additive/upsert based: it never deletes the local
SQLite database and can be run again after a failed network attempt.  Secrets
are read from .env and are never printed.
"""

from __future__ import annotations

import argparse
import os
import sqlite3
from pathlib import Path

import psycopg
from psycopg import sql


ROOT = Path(__file__).resolve().parents[1]
DB_PATH = Path(os.environ.get("CAMPUS_DB_PATH", str(ROOT / "campus_commons.sqlite3"))).expanduser()


def load_env() -> None:
    path = ROOT / ".env"
    if not path.exists():
        return
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key, value = key.strip(), value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "'\"":
            value = value[1:-1]
        os.environ.setdefault(key, value)


# The application stores JSON as TEXT.  Keeping that representation in the
# first migration means the existing server can read the cloud rows unchanged.
DDL = [
    """CREATE TABLE IF NOT EXISTS organizations (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL, short_name TEXT NOT NULL, kind TEXT NOT NULL,
      credit_score DOUBLE PRECISION NOT NULL DEFAULT 80,
      shared_hours DOUBLE PRECISION NOT NULL DEFAULT 0,
      available_hours DOUBLE PRECISION NOT NULL DEFAULT 0,
      allocations_won BIGINT NOT NULL DEFAULT 0,
      allocations_lost BIGINT NOT NULL DEFAULT 0,
      verified BIGINT NOT NULL DEFAULT 1, suspended BIGINT NOT NULL DEFAULT 0,
      created_at TEXT NOT NULL
    )""",
    """CREATE TABLE IF NOT EXISTS resources (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      owner_org_id BIGINT NOT NULL REFERENCES organizations(id),
      name TEXT NOT NULL, type TEXT NOT NULL, capability TEXT NOT NULL,
      features TEXT NOT NULL DEFAULT '', availability_start TEXT NOT NULL,
      availability_end TEXT NOT NULL, location TEXT NOT NULL,
      capacity DOUBLE PRECISION NOT NULL DEFAULT 1,
      condition TEXT NOT NULL DEFAULT 'Good', hourly_value DOUBLE PRECISION NOT NULL DEFAULT 0,
      external_hourly_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
      cost_source TEXT NOT NULL DEFAULT '', verified BIGINT NOT NULL DEFAULT 1,
      status TEXT NOT NULL DEFAULT 'available', created_at TEXT NOT NULL
    )""",
    """CREATE TABLE IF NOT EXISTS missions (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      requester_org_id BIGINT NOT NULL REFERENCES organizations(id),
      title TEXT NOT NULL, description TEXT NOT NULL, location TEXT NOT NULL,
      start_at TEXT NOT NULL, end_at TEXT NOT NULL, deadline TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'open', requirements TEXT NOT NULL DEFAULT '[]',
      plans TEXT NOT NULL DEFAULT '[]', preferences TEXT NOT NULL DEFAULT '[]',
      allocated_plan_id TEXT, replacement_pending BIGINT NOT NULL DEFAULT 0,
      created_at TEXT NOT NULL, updated_at TEXT NOT NULL
    )""",
    """CREATE TABLE IF NOT EXISTS events (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      kind TEXT NOT NULL, title TEXT NOT NULL, detail TEXT NOT NULL,
      created_at TEXT NOT NULL, audience_org_id BIGINT REFERENCES organizations(id)
    )""",
    """CREATE TABLE IF NOT EXISTS bookings (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      mission_id BIGINT NOT NULL REFERENCES missions(id), resource_id BIGINT NOT NULL REFERENCES resources(id),
      start_at TEXT NOT NULL, end_at TEXT NOT NULL, quantity DOUBLE PRECISION NOT NULL DEFAULT 1,
      status TEXT NOT NULL DEFAULT 'active', completed_at TEXT, created_at TEXT NOT NULL,
      UNIQUE(mission_id, resource_id)
    )""",
    """CREATE TABLE IF NOT EXISTS admin_config (
      id BIGINT PRIMARY KEY CHECK(id=1), scheduler_enabled BIGINT NOT NULL DEFAULT 0,
      interval_seconds BIGINT NOT NULL DEFAULT 300, weights TEXT NOT NULL DEFAULT '{}'
    )""",
    """CREATE TABLE IF NOT EXISTS demo_runs (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      started_at TEXT NOT NULL, finished_at TEXT NOT NULL, status TEXT NOT NULL, report TEXT NOT NULL
    )""",
    """CREATE TABLE IF NOT EXISTS decisions (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      mission_id BIGINT REFERENCES missions(id), urgency DOUBLE PRECISION,
      contribution DOUBLE PRECISION, credit DOUBLE PRECISION, access_fairness DOUBLE PRECISION,
      alternative_scarcity DOUBLE PRECISION, fairness_score DOUBLE PRECISION,
      submitted_preferences TEXT NOT NULL DEFAULT '[]', chosen_plan TEXT, outcome TEXT,
      explanation TEXT NOT NULL DEFAULT '', policy_snapshot TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL
    )""",
    """CREATE TABLE IF NOT EXISTS disputes (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      mission_id BIGINT NOT NULL REFERENCES missions(id), reporter_org_id BIGINT NOT NULL REFERENCES organizations(id),
      accused_org_id BIGINT REFERENCES organizations(id), category TEXT NOT NULL, description TEXT NOT NULL,
      compensation_amount DOUBLE PRECISION NOT NULL DEFAULT 0, evidence TEXT NOT NULL DEFAULT '[]',
      compensation_status TEXT NOT NULL DEFAULT 'not_requested', status TEXT NOT NULL DEFAULT 'open',
      created_at TEXT NOT NULL, resolved_at TEXT, resolved_by TEXT, resolution_description TEXT,
      approved_at TEXT, frozen_at TEXT, victim_resolved_at TEXT
    )""",
    """CREATE TABLE IF NOT EXISTS credit_events (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      organization_id BIGINT NOT NULL REFERENCES organizations(id), event_type TEXT NOT NULL,
      delta DOUBLE PRECISION NOT NULL, before_score DOUBLE PRECISION NOT NULL, after_score DOUBLE PRECISION NOT NULL,
      mission_id BIGINT REFERENCES missions(id), details TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL
    )""",
    """CREATE TABLE IF NOT EXISTS contribution_events (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      organization_id BIGINT NOT NULL REFERENCES organizations(id), event_type TEXT NOT NULL,
      hours DOUBLE PRECISION NOT NULL, resource_id BIGINT REFERENCES resources(id),
      mission_id BIGINT REFERENCES missions(id), details TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL
    )""",
    """CREATE TABLE IF NOT EXISTS history_log (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      entity_type TEXT NOT NULL, entity_id BIGINT NOT NULL, organization_id BIGINT REFERENCES organizations(id),
      action TEXT NOT NULL, snapshot TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL
    )""",
    """CREATE TABLE IF NOT EXISTS user_sessions (
      session_id TEXT PRIMARY KEY, organization_id BIGINT NOT NULL REFERENCES organizations(id),
      created_at TEXT NOT NULL, last_seen TEXT NOT NULL
    )""",
    "CREATE INDEX IF NOT EXISTS idx_history_org_time ON history_log(organization_id, created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_history_entity_time ON history_log(entity_type, entity_id, created_at DESC)",
]

TABLE_ORDER = [
    "organizations", "resources", "missions", "events", "bookings", "admin_config", "demo_runs",
    "decisions", "disputes", "credit_events", "contribution_events", "history_log", "user_sessions",
]


def main() -> int:
    load_env()
    dsn = os.environ.get("SUPABASE_DATABASE_URL", "").strip()
    if not dsn or "<YOUR-PASSWORD>" in dsn or "[YOUR-PASSWORD" in dsn:
        raise SystemExit("SUPABASE_DATABASE_URL 未配置完整。请先在 .env 中填入真实数据库密码。")
    if not DB_PATH.exists():
        raise SystemExit(f"找不到本地数据库：{DB_PATH}")

    parser = argparse.ArgumentParser(description="Migrate Campus Commons SQLite data to Supabase Postgres")
    parser.add_argument("--yes", action="store_true", help="skip the final confirmation prompt")
    args = parser.parse_args()
    if not args.yes:
        print(f"即将把 {DB_PATH.name} 的演示数据复制到 Supabase；本地文件不会删除。")
        if input("继续？输入 YES：").strip() != "YES":
            print("已取消。")
            return 0

    local = sqlite3.connect(DB_PATH)
    local.row_factory = sqlite3.Row
    try:
        counts = {table: local.execute(f'SELECT COUNT(*) FROM "{table}"').fetchone()[0] for table in TABLE_ORDER}
        with psycopg.connect(dsn, connect_timeout=15) as cloud:
            with cloud.cursor() as cur:
                for statement in DDL:
                    cur.execute(statement)
                for table in TABLE_ORDER:
                    rows = local.execute(f'SELECT * FROM "{table}"').fetchall()
                    if not rows:
                        continue
                    columns = list(rows[0].keys())
                    placeholders = ",".join(["%s"] * len(columns))
                    assignments = ",".join(f'{col}=EXCLUDED.{col}' for col in columns if col != ("session_id" if table == "user_sessions" else "id"))
                    conflict = "session_id" if table == "user_sessions" else "id"
                    query = sql.SQL("INSERT INTO {} ({}) VALUES ({}) ON CONFLICT ({}) DO UPDATE SET {}" ).format(
                        sql.Identifier(table), sql.SQL(",").join(map(sql.Identifier, columns)),
                        sql.SQL(placeholders), sql.Identifier(conflict), sql.SQL(assignments)
                    )
                    for row in rows:
                        cur.execute(query, tuple(row[col] for col in columns))
                # Explicit ids were copied; move identity sequences past them.
                for table in TABLE_ORDER:
                    if table == "admin_config" or table == "user_sessions":
                        continue
                    cur.execute("SELECT setval(pg_get_serial_sequence(%s, 'id'), COALESCE(MAX(id), 1), MAX(id) IS NOT NULL) FROM " + table, (table,))
            cloud.commit()
    finally:
        local.close()
    print("Supabase 数据迁移完成（本地 SQLite 保留）。")
    for table in TABLE_ORDER:
        print(f"  {table}: {counts[table]} 条")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
